name: astro_tak
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.6.1
  get_it: ^7.2.0
  dio: ^4.0.4
  flutter_bloc: ^8.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
flutter_intl:
  enabled: true
